pipeline {
    agent {
        docker { image 'busybox:1.34.1' }
    }
    stages {
        stage('Run') {
            steps {
                checkout scm
                sh 'echo "hello"'
            }
        }
    }
}
