name: Add review label
on:
  project_card:
    types:
      - moved
jobs:
  add-labels:
    runs-on: ubuntu-latest
    # https://github.com/gokken-roko/github-tutorials/projects/1#column-17292314
    if: github.event.project_card.column_id == '17292314'
    steps:
      - name: Add labels
        uses: actions/github-script@v5.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['triage/review']
            })
